users:
  - default
  - name: vmuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCj9UGehYXN/vnaD5kdDgiOuJJ/mesDuMVbDbI+5h1VUYabgmwMhZlmNAZJNmiThyaJA8XIOWi1RN4DP7he7OCvykW4aYo8qd+EqdPHBZKdq7Ti2mhfWyyWdoz/ddRXb9Y2DK+Gk2ZERF5j6gRRV6NMpeWkK8Zz4ReKsNpkpHG4+m1N+fFJp8bcB2TnS/H8aIY0aCxm8k721rik5+VpdOK57BOSWqWW/TwUOOATs1FkEQ+axXgnNDSTAArzjky7TIkzOiZ54Qi49UFqF9l402FC9W+3GIustV41u9dFHYdwfig8ZODkyvz698yO+jvm8XGxipmEYzjVm7DNXFa+yqn8nUhc/z6qB4vuu6ZVKdsrFt+OeUNIOpJjPMIoI7GtJu5EJEopal+cWy37ZeYzWO1ZeRpJVLOt/ce+HshuPZ6EIyHr2zhpyHDv/cJ2lNb+fl9+qLqlGmFfve6kgvxvMniauRiV2B0a2YjR9LEp/B2euQ8BwpeN5pW5FOOsSCudIM= vmuser
